Adding the possibility of controlling the elements that will be treated
phlib/xss-sanitizer pull request #9
Opened 2024-04-22 19:17 UTC by EmanuelAugusto

In this pr I added the possibility for the implementer to control attributes that will be treated in addition to those already implemented in the package.

2024-04-30 19:27 UTC, Pudge601 submitted a review, later dismissed
All looks good to me, thanks for the pull request!

2024-05-01 05:52 UTC, chrisminett requested changes
Thanks for the PR! I've added some minor tidy comments, but the main thing is to add/update unit tests to cover the new functionality.
I can have a look at that in the next few weeks, but please update if you're able. Thanks!

2024-05-01 05:52 UTC, chrisminett commented on src/Filter/RemoveAttributes.php
> +    public function __construct($attributes = [])
Can you add/update tests to cover this change, please?

2024-05-01 05:52 UTC, chrisminett commented on src/Sanitizer.php
> +    public function __construct(array $removeBlocks = [], array $removeAttributtes = [])
I added type declarations here, but online editor added too many spaces :doh:. Dev dependency requirements have ECS included which you can run locally to fix this and the missing declaration in `RemoveAttributes`.

```sh
./vendor/bin/ecs --fix
```

2024-05-01 05:52 UTC, chrisminett commented on src/Sanitizer.php
> +    public function __construct(array $removeBlocks = [], array $removeAttributtes = [])
Can you add/update tests to cover this change, please?

2024-05-01 05:52 UTC, chrisminett commented on src/Sanitizer.php
> +        $this->removeAttributtes = [...$this->removeAttributtes, ...$removeAttributtes];
This could be simplified as there's no default on the class. The class property doesn't need an initial value.

2024-06-08 05:23 UTC, merged

2024-06-08 06:24 UTC, chrisminett commented
@EmanuelAugusto I've added tests in #10 and this has been released as [2.1.0](https://github.com/phlib/xss-sanitizer/releases/tag/2.1.0).
Thanks!